version: '3.8'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    volumes:
      - .\jenkins_home:/var/jenkins_home
      - D:\PDS2025\LaravelProject:/var/jenkins_home/workspace/laravel 
    ports:
      - "9080:8080"
    networks:
      - backend
networks:
  backend:
    name: network_jenkins
